version: "3.8"

services:
  app:
    container_name: jumandi-admin-dev
    image: jumandi-admin-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    stdin_open: true